<?php

/**
 * @file
 * Drupoid main functions.
 */

/**
 * Implements hook_menu().
 */
function drupoid_menu() {
  $items = array();

  $items[variable_get('drupoid_endpoint', 'drupoid')] = array(
    'title' => 'Drupoid request',
    'page callback' => 'drupoid_request',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/media/drupoid'] = array(
    'title' => 'Drupoid',
    'description' => 'Configure the settings for Android application.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupoid_configuration'),
    'access arguments' => array('administer drupoid'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function drupoid_permission() {
  return array(
    'administer drupoid' => array(
      'title' => t('Administer Drupoid'),
      'description' => t('Configure your Drupoid settings')
    ),
    'upload images via app' => array(
      'title' => t('Upload images'),
      'description' => t('Give users the privilege to upload images from the application.')
    ),
  );
}

/**
 * Menu callback: configuration form.
 */
function drupoid_configuration($form, $form_state) {
  global $base_url;

  $form['drupoid_endpoint'] = array(
    '#title' => t('Endpoint'),
    '#description' => t('The end point URL for your request. Current endpoint is @end_point', array('@end_point' => $base_url . '/' . variable_get('drupoind_endpoint', 'drupoid'))),
    '#type' => 'textfield',
    '#default_value' => variable_get('drupoid_endpoint', 'drupoid'),
  );

  $options = array();
  $node_bundles = node_type_get_names();
  $instances = field_info_instances('node');
  foreach ($instances as $bundle => $fields) {
    foreach ($fields as $field_name => $field) {
      $field_info = field_info_field($field_name);
      if ($field_info['type'] == 'image') {
        $options[$bundle . '|' . $field_name] = $node_bundles[$bundle] . ': ' . $field['label'];
      }
    }
  }
  $form['drupoid_image_field'] = array(
    '#title' => t('Image field'),
    '#required' => TRUE,
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => variable_get('drupoid_image_field'),
  );

  $form['drupoid_status'] = array(
    '#title' => t('Publish immediately'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('drupoid_status'),
  );

  $form['drupoid_debug'] = array(
    '#title' => t('Log the $_POST & $_FILES variable to watchdog. Turn off in production.'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('drupoid_debug'),
  );

  return system_settings_form($form);
}

/**
 * Menu callback: do a drupoid request.
 */
function drupoid_request() {

  // Debug ?
  if (variable_get('drupoid_debug')) {
    watchdog('drupoid_debug_post', print_r($_POST, TRUE));
    watchdog('drupoid_debug_files', print_r($_FILES, TRUE));
  }

  // Determine request type.
  $request_type = drupoid_request_type();
  if (!$request_type) {
    drupoid_request_end(t('Invalid request type.'), WATCHDOG_WARNING);
  }

  // Check if the user is authenticated.
  if ($GLOBALS['user']->uid == 0 && $request_type != "authenticate") {
    drupal_add_http_header('Status', '403 Forbidden');
    drupoid_request_end(t('Could not authenticate this request. Please login via the settings menu.'), WATCHDOG_WARNING);
  }

  // Delegate to separate function.
  $callback = 'drupoid_service_'  . $request_type;
  $result = $callback();
  drupoid_request_end($result['toast'], $result['severity']);
}

/**
 * Function to determine the request type.
 */
function drupoid_request_type() {

  $request_type = isset($_POST['request_type']) ? $_POST['request_type'] : FALSE;

  if (in_array($request_type, array('authenticate', 'image_upload'))) {
    return $request_type;
  }

  return FALSE;
}

/**
 * End the Drupoid request.
 *
 * @param $toast
 *   A string to send back to the application and log to watchdog.
 * @param $severity
 *   A watchdog constant.
 */
function drupoid_request_end($toast, $severity) {
  // Ignore devel.
  $GLOBALS['devel_shutdown'] = FALSE;
  // Commit the user session, if needed.
  drupal_session_commit();
  // Write watchdog and print result.
  watchdog('drupoid', $toast, array(), $severity);
  print $toast;
  exit();
}

/**
 * Drupoid authentication service.
 */
function drupoid_service_authenticate() {

  // We need 2 variables at least.
  if (!isset($_POST['drupoid_username']) || !isset($_POST['drupoid_password'])) {
    return array(
      'toast' => t('No username or password supplied.'),
      'severity' => WATCHDOG_WARNING
    );
  }

  // Authenticate.
  if ($uid = user_authenticate($_POST['drupoid_username'], $_POST['drupoid_password'])) {
    global $user;
    $edit = array();
    $user = user_load($uid);
    user_login_finalize($edit);
    return array(
      'toast' => t('Authentication succeeded for @user', array('@user' => $_POST['drupoid_username'])),
      'severity' => WATCHDOG_NOTICE
    );
  }

  return array(
    'toast' => t('Sorry, unrecognized username or password.'),
    'severity' => WATCHDOG_NOTICE
  );
}

/**
 * Drupoid logout service.
 */
function drupoid_service_logout() {
  global $user;

  if ($user->uid > 0) {
    $name = $user->name;

    // Invoke user_logout hook.
    module_invoke_all('user_logout', $user);

    // Destroy the current session, and reset $user to the anonymous user.
    session_destroy();

    return array(
      'toast' => t('Session closed for %name.', array('%name' => $name)),
      'severity' => WATCHDOG_NOTICE
    );
  }
  else {
    return array(
      'toast' => t('Session already closed'),
      'severity' => WATCHDOG_NOTICE
    );
  }
}

/**
 * Drupoid image upload service.
 */
function drupoid_service_image_upload() {

  // Access
  if (!user_access('upload images via app')) {
    // @todo this could be nicer. we already have a 403 above.
    drupal_add_http_header('Status', '403 Forbidden');
    return array(
      'severity' => WATCHDOG_NOTICE,
      'toast' => t('User has no permission to upload images.'),
    );
  }

  // Title send through ?
  if (!isset($_POST['title'])) {
    return array(
      'severity' => WATCHDOG_NOTICE,
      'toast' => t('No title found in request.'),
    );
  }

  // Image send through ?
  if (!isset($_FILES['image']['name'])) {
    return array(
      'severity' => WATCHDOG_NOTICE,
      'toast' => t('No image found in request.'),
    );
  }

  // Is the drupoid_image_field variable set.
  if (!variable_get('drupoid_image_field')) {
    return array(
      'severity' => WATCHDOG_NOTICE,
      'toast' => t('No image field set. Configure it on your Drupal installation.'),
    );
  }

  // Basic checks are ok. Let's move on.
  $severity = WATCHDOG_NOTICE;

  // Try to save the node and file.
  if ($file = _drupoid_save_upload('image')) {

    // Build node.
    list($bundle, $image_field_name) = explode('|', variable_get('drupoid_image_field'));
    $node = new stdClass();
    $node->title = $_POST['title'];
    $node->type = $bundle;
    $node->status = variable_get('drupoid_status', FALSE);
    $node->name = $GLOBALS['user']->name;
    $node->language = LANGUAGE_NONE;
    $node->{$image_field_name}[LANGUAGE_NONE][0] = (array) $file;

    // Save the node.
    node_submit($node);
    node_save($node);
    if ($node->nid) {
      $toast = t('Image has been posted.');
      cache_clear_all();
    }
    else {
      $severity = WATCHDOG_WARNING;
      $toast = t('Error saving new node.');
    }
  }
  else {
    $severity = WATCHDOG_WARNING;
    $toast = t('Image file could not be saved.');
  }

  return array(
    'severity' => $severity,
    'toast' => $toast,
  );
}

/**
 * Helper function to upload an image.
 *
 * @param $image_key
 *   The key in the $_FILES variable to look for
 *   the image.
 */
function _drupoid_save_upload($image_key) {

  $destination = 'android_' . time() . '.jpg';

  // We need to manipulate the $_FILES array so file.inc can handle it.
  $_FILES['files']['name'][$image_key] = $destination;
  $_FILES['files']['error'][$image_key] = $_FILES[$image_key]['error'];
  $_FILES['files']['tmp_name'][$image_key] = $_FILES[$image_key]['tmp_name'];
  $_FILES['files']['size'][$image_key] = $_FILES[$image_key]['size'];

  // Create destination and save the file.
  return file_save_upload($image_key, array(), "public://");
}